title: libmicrohttpd-HTTP2
name: "Maru Berezin"
description: "An HTTP/2 implementation for GNU libmicrohttpd"
url: "https://maru.github.io"
baseurl: "/libmicrohttpd-http2"
repository: "maru/libmicrohttpd-http2"

show_downloads: true
highlighter: rouge
markdown: kramdown

logo: /static/img/logo.jpg

# breadcrumbs: false
# search: true
# search_full_content: true
include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "navbar"
