title: libmicrohttpd-HTTP2
name: "Maru Berezin"
description: "An HTTP/2 implementation for GNU libmicrohttpd"
url: "https://maru.github.io"
baseurl: "/libmicrohttpd-http2"
repository: "maru/libmicrohttpd-http2"

logo: /assets/img/logo.jpg
show_downloads: true
highlighter: rouge
markdown: kramdown

#theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes"

# breadcrumbs: false
# search: true
# search_full_content: true
include: ["_pages"]
permalink: /:slug/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "docs"
